"""Generate slides/slides.md from site/meshtastic.md + slides/notes.md.

One source of truth. site/meshtastic.md is the deck; slides/notes.md carries
the hidden speaker notes keyed by slide number. This script rewrites
slides/slides.md in the dialect scripts/build-deck.py reads, so the offline
deck/deck.html and the cpuchip.net deck cannot drift apart again.

Usage: python scripts/sync-slides.py && python scripts/build-deck.py
"""
import io
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "site" / "meshtastic.md"
NOTES = ROOT / "slides" / "notes.md"
OUT = ROOT / "slides" / "slides.md"

IMG = re.compile(r"^!\[[^\]]*\]\(/images/presentations/meshtastic/([\w\-.]+)\)\s*$")
DIAG = re.compile(r"^\{\{diagram:([a-z0-9-]+)\}\}\s*$")
NOWRAP = re.compile(r'<span style="white-space: nowrap">(.*?)</span>')


def load_notes():
    notes, cur = {}, None
    for line in io.open(NOTES, encoding="utf-8").read().splitlines():
        m = re.match(r"^## Slide (\d+)\s*$", line)
        if m:
            cur = int(m.group(1))
            notes[cur] = []
            continue
        if line.startswith("# "):
            cur = None
            continue
        if cur is not None and line.strip():
            notes[cur].append(line.strip())
    return notes


def convert(block, n, notes):
    out, imgs = [], []
    for line in block.splitlines():
        s = line.rstrip()
        t = s.strip()
        if not t or t.startswith("<div") or t.startswith("</div") or t.startswith("<!--"):
            continue
        m = IMG.match(t)
        if m:
            imgs.append(m.group(1))
            continue
        m = DIAG.match(t)
        if m:
            imgs.append(m.group(1) + ".svg")
            continue
        s = NOWRAP.sub(r"\1", s)
        if s.startswith("## "):
            s = "### " + s[3:]
        # A whole-line italic is a visible caption on the site deck but a hidden
        # note in the offline dialect, so it becomes a plain line here.
        if re.fullmatch(r"\*[^*].*[^*]\*", s.strip()):
            s = s.strip()[1:-1]
        out.append(s)
    h1 = next((o for o in out if o.startswith("# ")), "")
    label = re.sub(r"<[^>]+>", " ", h1[2:])
    label = re.sub(r"[*_`]", "", label)
    label = re.sub(r"\s+", " ", label).strip()
    heads = [o for o in out if o.startswith("# ")]
    rest = [o for o in out if not o.startswith("# ")]
    body = [f"## SLIDE {n} - {label}", ""] + heads
    if imgs:
        if len(imgs) == 1:
            kind = "diagram" if imgs[0].endswith(".svg") else "image"
            body += ["", f"({kind}: {imgs[0]})"]
        else:
            body += ["", f"({len(imgs)}-up: " + " · ".join(imgs) + ")"]
    if rest:
        body.append("")
        # The offline builder joins any line that does not start a new block onto
        # the previous line, so every heading, paragraph and table gets a blank
        # line before it; only consecutive list items and table rows stay adjacent.
        prev_kind = None
        for o in rest:
            kind = ("li" if (o.startswith("- ") or re.match(r"^\d+\.\s", o))
                    else "tr" if o.startswith("|") else "block")
            if body[-1] != "" and (kind == "block" or kind != prev_kind):
                body.append("")
            body.append(o)
            prev_kind = kind
    for note in notes.get(n, []):
        body += ["", f"*{note}*"]
    return "\n".join(body)


def main():
    text = io.open(SRC, encoding="utf-8").read()
    if text.startswith("---"):
        text = text[text.index("\n---\n", 3) + 5:]
    blocks = [b.strip() for b in text.split("\n---\n") if b.strip()]
    notes = load_notes()
    header = (
        "# Slides (GENERATED by scripts/sync-slides.py from site/meshtastic.md + slides/notes.md)\n\n"
        "Do not edit. Change the deck in site/meshtastic.md and the speaker notes in\n"
        "slides/notes.md, then run: python scripts/sync-slides.py && python scripts/build-deck.py\n"
    )
    slides = [convert(b, i + 1, notes) for i, b in enumerate(blocks)]
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(
        header + "\n---\n\n" + "\n\n---\n\n".join(slides) + "\n"
    )
    used = sorted(k for k in notes if k <= len(blocks))
    unused = sorted(k for k in notes if k > len(blocks))
    msg = f"OK: {len(blocks)} slides -> {OUT.relative_to(ROOT)}; notes on {used}"
    if unused:
        msg += f"; NOTES WITH NO SLIDE: {unused}"
    print(msg)


if __name__ == "__main__":
    main()
