"""Sync the deck + assets into the cpuchip.net repo.

Source of truth stays HERE (the mesh repo); cpuchip.net receives copies:
  site/meshtastic.md  -> ../cpuchip.net/content/slides/meshtastic.md
                         ({{diagram:name}} tokens inlined from assets/diagrams/)
  assets/images/*     -> ../cpuchip.net/public/images/presentations/meshtastic/

Run from anywhere: paths are derived from this file's location.
Fails loudly if a diagram token doesn't resolve or a referenced image is missing.
"""

import re
import shutil
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT.parent / "cpuchip.net"
DECK_SRC = ROOT / "site" / "meshtastic.md"
DECK_DST = SITE / "content" / "slides" / "meshtastic.md"
IMG_SRC = ROOT / "assets" / "images"
IMG_DST = SITE / "public" / "images" / "presentations" / "meshtastic"
DIAGRAMS = ROOT / "assets" / "diagrams"

def main() -> int:
    if not SITE.is_dir():
        print(f"FAIL: site repo not found at {SITE}")
        return 1

    text = DECK_SRC.read_text(encoding="utf-8")

    # Inline diagrams
    def inline(m: re.Match) -> str:
        svg = DIAGRAMS / f"{m.group(1)}.svg"
        if not svg.is_file():
            raise FileNotFoundError(f"diagram token '{m.group(1)}' has no file at {svg}")
        return f'<div class="slide-diagram">\n{svg.read_text(encoding="utf-8").strip()}\n</div>'

    text = re.sub(r"\{\{diagram:([a-z0-9-]+)\}\}", inline, text)
    leftover = re.findall(r"\{\{[^}]*\}\}", text)
    if leftover:
        print(f"FAIL: unresolved tokens remain: {leftover}")
        return 1

    # Verify every referenced local image exists in assets/images
    missing = []
    for ref in re.findall(r"/images/presentations/meshtastic/([\w.-]+)", text):
        if not (IMG_SRC / ref).is_file():
            missing.append(ref)
    if missing:
        print(f"FAIL: deck references images not in assets/images: {missing}")
        return 1

    # Stamp provenance (after frontmatter so gray-matter still parses)
    text = re.sub(
        r"^(---\n.*?\n---\n)",
        r"\1\n<!-- GENERATED by meshtastic-presentation-2026/scripts/sync-to-site.py"
        " — edit site/meshtastic.md THERE, not this file. -->\n",
        text, count=1, flags=re.S,
    )

    DECK_DST.parent.mkdir(parents=True, exist_ok=True)
    DECK_DST.write_text(text, encoding="utf-8", newline="\n")

    IMG_DST.mkdir(parents=True, exist_ok=True)
    copied = 0
    for f in IMG_SRC.iterdir():
        if f.is_file():
            shutil.copy2(f, IMG_DST / f.name)
            copied += 1

    n_slides = len(re.split(r"\n---\n", text.split("---\n", 2)[2])) if text.startswith("---") else 0
    print(f"OK: deck -> {DECK_DST} ({n_slides} slides, diagrams inlined); {copied} images -> {IMG_DST}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
